#!/bin/sh

# git (in addition to https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh)
alias gundo='git reset --soft HEAD^'
alias glast='git log -1 HEAD'
alias gd='git diff'
alias gcleanup='git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d'
alias gs='git status'
alias _r='source ~/.zshrc'
alias edot='atom ~/.dotfiles'
alias rr='bundle exec rubocop -A'
alias gbs='git for-each-ref --sort=-committerdate refs/heads/'

# Unix
alias l="gls -lAh --color"
alias ll="gls -l --color"
alias mkdir="mkdir -p"
alias e="$EDITOR"
alias eme="e ~/work/me"
alias vim=nvim
alias v="$VISUAL"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Bundler
alias be="bundle exec"
alias bi="bundle install"

# Bash
alias reload!='. ~/.zshrc'
