#!/bin/sh

# git (in addition to https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh)
alias gundo='git reset --soft HEAD^'
alias glast='git log -1 HEAD'
alias gunstage='git reset HEAD --'
alias gd='git diff'
alias gcleanup='git branch -d `git branch --merged | grep -v "^*" | grep -v "master" | tr -d "\n"`'
alias gs='git status'

# Unix
alias l="gls -lAh --color"
alias ll="gls -l --color"
alias mkdir="mkdir -p"
alias e="$EDITOR"
alias edot="atom ~/.dotfiles"
alias eme="atom ~/work/me"
alias v="$VISUAL"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Bundler
alias be="bundle exec"
alias bi="bundle install"

# Bash
alias path='echo $PATH | tr -s ":" "\n"'
alias reload!='. ~/.zshrc'

#tmuxalias ta='tmux attach -t'
alias tad='tmux attach -d -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'

alias tkss='tmux kill-session -t'

# GDS Vagrant and ENV
alias start="cd ~/work/govuk/govuk-puppet/development-vm && vagrant up"
alias dev="ssh dev"
