#!/bin/sh

# Unix
alias l="gls -lAh --color"
alias ll="gls -l --color"
alias mkdir="mkdir -p"
alias e="$EDITOR"
alias v="$VISUAL"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Bundler
alias be="bundle exec"
alias bi="bundle install"

# Bash
alias path='echo $PATH | tr -s ":" "\n"'
alias reload!='. ~/.zshrc'
